version: '3.9'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/react-study # ローカルをコンテナ内にマウント
      - volume1:/react-study/node_modules
    ports:
      - 5173:5173
      - 5174:5174
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true 
volumes:
  volume1: